extend type Booking {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Booking", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`tour`. It must match the value of `Tour`.`id`. See `@ref` for how to customize it.
  """
  tourId: UUID! @fdc_generated(from: "Booking.tour", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Booking.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Guide {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Guide", purpose: IMPLICIT_KEY_FIELD)
}
extend type Tour {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Tour", purpose: IMPLICIT_KEY_FIELD)
}
extend type TourAssignment {
  """
  ✨ Implicit foreign key field based on `TourAssignment`.`tour`. It must match the value of `Tour`.`id`. See `@ref` for how to customize it.
  """
  tourId: UUID! @fdc_generated(from: "TourAssignment.tour", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `TourAssignment`.`guide`. It must match the value of `Guide`.`id`. See `@ref` for how to customize it.
  """
  guideId: UUID! @fdc_generated(from: "TourAssignment.guide", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
